#######################################################################################
# Book settings
title : OCIBook
author: David Da SILVA
logo: 'leC.png'

# Information about where the book exists on the web
description: >-
  Une introduction au langage Python

#######################################################################################
# MyST parsing settings
#parse:
#  myst_extended_syntax: true

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : auto
    #execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar         : false
  extra_footer: |
    <p>
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
    </a>
    <br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
    Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
    </a>.
    </p>

#######################################################################################
sphinx:
  config:
    html_show_copyright: false
    language: fr
    html_theme: sphinx_book_theme
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_favicon: python.ico
    myst_enable_extensions:
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      - html_admonition
      - html_image
      - linkify
      - replacements
      - smartquotes
      - substitution


# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Information about where the book exists on the web
repository:
  url                       : https://github.com/dasilvadds/OCIBook.git # Online location of your book
#  path_to_book              : _build/html  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

# Launch button settings
launch_buttons:
  notebook_interface: "classic" # or "jupyterlab"

#binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: OCI_Python.tex
