#######################################################################################
# Book settings
title : OCI - Introduction à Python
author: David Da SILVA
logo: 'leC.png'

# Information about where the book exists on the web
description: >-
  Une introduction au langage Python pour le cours d'Option Complémentaire Informatique au gymnase.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
#repository:
#  url                         : https://github.com/executablebooks/quantecon-mini-example
#  path_to_book                : "mini_book"
#
#binder:
#  binderhub_url               : "https://mybinder.org"
#  text                        : "Launch binder"
#
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
